import React from 'react';
import WordSearchComponent from '../components/WordSearchComponent';

const wordsearch = [[{value:'Z',correct:0},{value:'D',correct:0},{value:'E',correct:0},{value:'S',correct:0},{value:'A',correct:0},{value:'S',correct:0},{value:'O',correct:0},{value:'S',correct:0},{value:'E',correct:0},{value:'G',correct:0},{value:'A',correct:0},{value:'R',correct:0},{value:'A',correct:0},{value:'M',correct:0},{value:'E',correct:0},{value:'D',correct:0},{value:'E',correct:0},{value:'X',correct:0},{value:'I',correct:0},{value:'M',correct:0},{value:'P',correct:0},{value:'A',correct:0},{value:'R',correct:0},{value:'R',correct:0},{value:'A',correct:0},{value:'N',correct:0},{value:'D',correct:0},{value:'E',correct:0},{value:'R',correct:0},{value:'O',correct:0}],
[{value:'U',correct:0},{value:'Z',correct:0},{value:'X',correct:0},{value:'A',correct:0},{value:'B',correct:0},{value:'L',correct:0},{value:'A',correct:0},{value:'T',correct:0},{value:'S',correct:0},{value:'E',correct:0},{value:'I',correct:0},{value:'T',correct:0},{value:'A',correct:0},{value:'P',correct:0},{value:'A',correct:0},{value:'R',correct:0},{value:'T',correct:0},{value:'B',correct:0},{value:'X',correct:0},{value:'O',correct:0},{value:'C',correct:0},{value:'S',correct:0},{value:'U',correct:0},{value:'D',correct:0},{value:'R',correct:0},{value:'A',correct:0},{value:'P',correct:0},{value:'H',correct:0},{value:'R',correct:0},{value:'F',correct:0}],
[{value:'O',correct:0},{value:'O',correct:0},{value:'P',correct:0},{value:'D',correct:0},{value:'I',correct:0},{value:'U',correct:0},{value:'J',correct:0},{value:'I',correct:0},{value:'E',correct:0},{value:'R',correct:0},{value:'F',correct:0},{value:'M',correct:0},{value:'A',correct:0},{value:'N',correct:0},{value:'R',correct:0},{value:'E',correct:0},{value:'S',correct:0},{value:'A',correct:0},{value:'N',correct:0},{value:'O',correct:0},{value:'C',correct:0},{value:'I',correct:0},{value:'L',correct:0},{value:'A',correct:0},{value:'X',correct:0},{value:'I',correct:0},{value:'A',correct:0},{value:'L',correct:0},{value:'R',correct:0},{value:'C',correct:0}],
[{value:'R',correct:0},{value:'G',correct:0},{value:'E',correct:0},{value:'K',correct:0},{value:'A',correct:0},{value:'C',correct:0},{value:'E',correct:0},{value:'E',correct:0},{value:'T',correct:0},{value:'N',correct:0},{value:'A',correct:0},{value:'C',correct:0},{value:'I',correct:0},{value:'R',correct:0},{value:'B',correct:0},{value:'U',correct:0},{value:'L',correct:0},{value:'O',correct:0},{value:'T',correct:0},{value:'U',correct:0},{value:'A',correct:0},{value:'B',correct:0},{value:'O',correct:0},{value:'D',correct:0},{value:'U',correct:0},{value:'T',correct:0},{value:'N',correct:0},{value:'E',correct:0},{value:'D',correct:0},{value:'E',correct:0}],
[{value:'E',correct:0},{value:'S',correct:0},{value:'D',correct:0},{value:'H',correct:0},{value:'R',correct:0},{value:'A',correct:0},{value:'N',correct:0},{value:'N',correct:0},{value:'B',correct:0},{value:'G',correct:0},{value:'Q',correct:0},{value:'A',correct:0},{value:'D',correct:0},{value:'I',correct:0},{value:'C',correct:0},{value:'U',correct:0},{value:'L',correct:0},{value:'N',correct:0},{value:'A',correct:0},{value:'L',correct:0},{value:'E',correct:0},{value:'T',correct:0},{value:'U',correct:0},{value:'A',correct:0},{value:'C',correct:0},{value:'B',correct:0},{value:'J',correct:0},{value:'X',correct:0},{value:'C',correct:0},{value:'B',correct:0}],
[{value:'R',correct:0},{value:'E',correct:0},{value:'I',correct:0},{value:'R',correct:0},{value:'M',correct:0},{value:'R',correct:0},{value:'I',correct:0},{value:'E',correct:0},{value:'T',correct:0},{value:'M',correct:0},{value:'A',correct:0},{value:'T',correct:0},{value:'A',correct:0},{value:'D',correct:0},{value:'O',correct:0},{value:'U',correct:0},{value:'O',correct:0},{value:'D',correct:0},{value:'I',correct:0},{value:'D',correct:0},{value:'N',correct:0},{value:'E',correct:0},{value:'R',correct:0},{value:'P',correct:0},{value:'M',correct:0},{value:'O',correct:0},{value:'C',correct:0},{value:'N',correct:0},{value:'I',correct:0},{value:'O',correct:0}],
[{value:'B',correct:0},{value:'I',correct:0},{value:'C',correct:0},{value:'O',correct:0},{value:'E',correct:0},{value:'U',correct:0},{value:'Y',correct:0},{value:'S',correct:0},{value:'D',correct:0},{value:'R',correct:0},{value:'I',correct:0},{value:'Ü',correct:0},{value:'G',correct:0},{value:'A',correct:0},{value:'M',correct:0},{value:'Y',correct:0},{value:'V',correct:0},{value:'H',correct:0},{value:'O',correct:0},{value:'D',correct:0},{value:'I',correct:0},{value:'Ñ',correct:0},{value:'A',correct:0},{value:'G',correct:0},{value:'G',correct:0},{value:'L',correct:0},{value:'E',correct:0},{value:'G',correct:0},{value:'A',correct:0},{value:'L',correct:0}],
[{value:'A',correct:0},{value:'R',correct:0},{value:'I',correct:0},{value:'D',correct:0},{value:'N',correct:0},{value:'D',correct:0},{value:'J',correct:0},{value:'R',correct:0},{value:'A',correct:0},{value:'I',correct:0},{value:'E',correct:0},{value:'R',correct:0},{value:'A',correct:0},{value:'M',correct:0},{value:'S',correct:0},{value:'U',correct:0},{value:'H',correct:0},{value:'I',correct:0},{value:'U',correct:0},{value:'A',correct:0},{value:'R',correct:0},{value:'E',correct:0},{value:'I',correct:0},{value:'R',correct:0},{value:'B',correct:0},{value:'A',correct:0},{value:'S',correct:0},{value:'E',correct:0},{value:'D',correct:0},{value:'L',correct:0}],
[{value:'L',correct:0},{value:'R',correct:0},{value:'O',correct:0},{value:'A',correct:0},{value:'I',correct:0},{value:'A',correct:0},{value:'O',correct:0},{value:'O',correct:0},{value:'R',correct:0},{value:'L',correct:0},{value:'F',correct:0},{value:'S',correct:0},{value:'R',correct:0},{value:'A',correct:0},{value:'H',correct:0},{value:'C',correct:0},{value:'U',correct:0},{value:'L',correct:0},{value:'S',correct:0},{value:'O',correct:0},{value:'I',correct:0},{value:'U',correct:0},{value:'O',correct:0},{value:'Ñ',correct:0},{value:'E',correct:0},{value:'Ü',correct:0},{value:'G',correct:0},{value:'I',correct:0},{value:'D',correct:0},{value:'E',correct:0}],
[{value:'P',correct:0},{value:'T',correct:0},{value:'N',correct:0},{value:'M',correct:0},{value:'A',correct:0},{value:'L',correct:0},{value:'S',correct:0},{value:'M',correct:0},{value:'T',correct:0},{value:'M',correct:0},{value:'P',correct:0},{value:'I',correct:0},{value:'E',correct:0},{value:'Q',correct:0},{value:'J',correct:0},{value:'U',correct:0},{value:'A',correct:0},{value:'L',correct:0},{value:'O',correct:0},{value:'I',correct:0},{value:'R',correct:0},{value:'A',correct:0},{value:'M',correct:0},{value:'A',correct:0},{value:'N',correct:0},{value:'I',correct:0},{value:'D',correct:0},{value:'A',correct:0},{value:'B',correct:0},{value:'T',correct:0}],
[{value:'H',correct:0},{value:'L',correct:0},{value:'I',correct:0},{value:'A',correct:0},{value:'S',correct:0},{value:'P',correct:0},{value:'E',correct:0},{value:'A',correct:0},{value:'E',correct:0},{value:'N',correct:0},{value:'C',correct:0},{value:'A',correct:0},{value:'D',correct:0},{value:'F',correct:0},{value:'R',correct:0},{value:'A',correct:0},{value:'I',correct:0},{value:'L',correct:0},{value:'I',correct:0},{value:'B',correct:0},{value:'B',correct:0},{value:'A',correct:0},{value:'E',correct:0},{value:'M',correct:0},{value:'A',correct:0},{value:'E',correct:0},{value:'L',correct:0},{value:'O',correct:0},{value:'P',correct:0},{value:'A',correct:0}],
[{value:'Q',correct:0},{value:'A',correct:0},{value:'A',correct:0},{value:'M',correct:0},{value:'F',correct:0},{value:'M',correct:0},{value:'M',correct:0},{value:'D',correct:0},{value:'S',correct:0},{value:'G',correct:0},{value:'L',correct:0},{value:'O',correct:0},{value:'A',correct:0},{value:'T',correct:0},{value:'A',correct:0},{value:'P',correct:0},{value:'O',correct:0},{value:'L',correct:0},{value:'I',correct:0},{value:'H',correct:0},{value:'A',correct:0},{value:'L',correct:0},{value:'J',correct:0},{value:'E',correct:0},{value:'U',correct:0},{value:'Q',correct:0},{value:'O',correct:0},{value:'R',correct:0},{value:'R',correct:0},{value:'A',correct:0}],
[{value:'L',correct:0},{value:'N',correct:0},{value:'R',correct:0},{value:'T',correct:0},{value:'S',correct:0},{value:'E',correct:0},{value:'A',correct:0},{value:'I',correct:0},{value:'A',correct:0},{value:'A',correct:0},{value:'C',correct:0},{value:'T',correct:0},{value:'U',correct:0},{value:'A',correct:0},{value:'L',correct:0},{value:'M',correct:0},{value:'E',correct:0},{value:'N',correct:0},{value:'T',correct:0},{value:'E',correct:0},{value:'Y',correct:0},{value:'F',correct:0},{value:'E',correct:0},{value:'G',correct:0},{value:'N',correct:0},{value:'O',correct:0},{value:'D',correct:0},{value:'U',correct:0},{value:'I',correct:0},{value:'V',correct:0}],
[{value:'C',correct:0},{value:'O',correct:0},{value:'A',correct:0},{value:'N',correct:0},{value:'E',correct:0},{value:'T',correct:0},{value:'N',correct:0},{value:'Z',correct:0},{value:'N',correct:0},{value:'A',correct:0},{value:'C',correct:0},{value:'Z',correct:0},{value:'E',correct:0},{value:'P',correct:0},{value:'M',correct:0},{value:'E',correct:0},{value:'V',correct:0},{value:'F',correct:0},{value:'O',correct:0},{value:'I',correct:0},{value:'R',correct:0},{value:'O',correct:0},{value:'T',correct:0},{value:'A',correct:0},{value:'R',correct:0},{value:'E',correct:0},{value:'P',correct:0},{value:'O',correct:0},{value:'T',correct:0},{value:'B',correct:0}],
[{value:'U',correct:0},{value:'S',correct:0},{value:'P',correct:0},{value:'R',correct:0},{value:'A',correct:0},{value:'M',correct:0},{value:'U',correct:0},{value:'O',correct:0},{value:'A',correct:0},{value:'S',correct:0},{value:'C',correct:0},{value:'R',correct:0},{value:'O',correct:0},{value:'S',correct:0},{value:'S',correct:0},{value:'O',correct:0},{value:'E',correct:0},{value:'H',correct:0},{value:'C',correct:0},{value:'A',correct:0},{value:'M',correct:0},{value:'E',correct:0},{value:'R',correct:0},{value:'R',correct:0},{value:'O',correct:0},{value:'R',correct:0},{value:'U',correct:0},{value:'T',correct:0},{value:'N',correct:0},{value:'E',correct:0}],
[{value:'V',correct:0},{value:'A',correct:0},{value:'R',correct:0},{value:'O',correct:0},{value:'L',correct:0},{value:'R',correct:0},{value:'E',correct:0},{value:'F',correct:0},{value:'D',correct:0},{value:'F',correct:0},{value:'E',correct:0},{value:'E',correct:0},{value:'A',correct:0},{value:'S',correct:0},{value:'T',correct:0},{value:'R',correct:0},{value:'O',correct:0},{value:'L',correct:0},{value:'O',correct:0},{value:'G',correct:0},{value:'A',correct:0},{value:'R',correct:0},{value:'X',correct:0},{value:'E',correct:0},{value:'M',correct:0},{value:'C',correct:0},{value:'A',correct:0},{value:'L',correct:0},{value:'D',correct:0},{value:'A',correct:0}],
[{value:'H',correct:0},{value:'C',correct:0},{value:'O',correct:0},{value:'D',correct:0},{value:'S',correct:0},{value:'A',correct:0},{value:'L',correct:0},{value:'Q',correct:0},{value:'O',correct:0},{value:'Z',correct:0},{value:'L',correct:0},{value:'F',correct:0},{value:'A',correct:0},{value:'G',correct:0},{value:'Z',correct:0},{value:'B',correct:0},{value:'I',correct:0},{value:'T',correct:0},{value:'J',correct:0},{value:'G',correct:0},{value:'A',correct:0},{value:'Ñ',correct:0},{value:'E',correct:0},{value:'N',correct:0},{value:'Q',correct:0},{value:'I',correct:0},{value:'G',correct:0},{value:'U',correct:0},{value:'A',correct:0},{value:'N',correct:0}],
[{value:'A',correct:0},{value:'U',correct:0},{value:'R',correct:0},{value:'A',correct:0},{value:'O',correct:0},{value:'L',correct:0},{value:'B',correct:0},{value:'Q',correct:0},{value:'E',correct:0},{value:'R',correct:0},{value:'A',correct:0},{value:'I',correct:0},{value:'A',correct:0},{value:'M',correct:0},{value:'N',correct:0},{value:'N',correct:0},{value:'J',correct:0},{value:'E',correct:0},{value:'T',correct:0},{value:'N',correct:0},{value:'U',correct:0},{value:'T',correct:0},{value:'H',correct:0},{value:'S',correct:0},{value:'I',correct:0},{value:'E',correct:0},{value:'T',correct:0},{value:'S',correct:0},{value:'I',correct:0},{value:'H',correct:0}],
[{value:'C',correct:0},{value:'M',correct:0},{value:'R',correct:0},{value:'T',correct:0},{value:'R',correct:0},{value:'I',correct:0},{value:'M',correct:0},{value:'M',correct:0},{value:'C',correct:0},{value:'V',correct:0},{value:'O',correct:0},{value:'H',correct:0},{value:'Q',correct:0},{value:'R',correct:0},{value:'B',correct:0},{value:'Y',correct:0},{value:'A',correct:0},{value:'R',correct:0},{value:'S',correct:0},{value:'E',correct:0},{value:'O',correct:0},{value:'A',correct:0},{value:'I',correct:0},{value:'E',correct:0},{value:'B',correct:0},{value:'S',correct:0},{value:'I',correct:0},{value:'X',correct:0},{value:'I',correct:0},{value:'E',correct:0}],
[{value:'D',correct:0},{value:'E',correct:0},{value:'A',correct:0},{value:'N',correct:0},{value:'A',correct:0},{value:'T',correct:0},{value:'R',correct:0},{value:'T',correct:0},{value:'A',correct:0},{value:'U',correct:0},{value:'E',correct:0},{value:'B',correct:0},{value:'C',correct:0},{value:'U',correct:0},{value:'D',correct:0},{value:'I',correct:0},{value:'B',correct:0},{value:'G',correct:0},{value:'E',correct:0},{value:'T',correct:0},{value:'D',correct:0},{value:'I',correct:0},{value:'R',correct:0},{value:'R',correct:0},{value:'M',correct:0},{value:'O',correct:0},{value:'L',correct:0},{value:'I',correct:0},{value:'T',correct:0},{value:'E',correct:0}],
[{value:'N',correct:0},{value:'M',correct:0},{value:'T',correct:0},{value:'O',correct:0},{value:'D',correct:0},{value:'O',correct:0},{value:'A',correct:0},{value:'Y',correct:0},{value:'S',correct:0},{value:'T',correct:0},{value:'E',correct:0},{value:'L',correct:0},{value:'R',correct:0},{value:'A',correct:0},{value:'I',correct:0},{value:'I',correct:0},{value:'E',correct:0},{value:'C',correct:0},{value:'R',correct:0},{value:'A',correct:0},{value:'R',correct:0},{value:'E',correct:0},{value:'P',correct:0},{value:'D',correct:0},{value:'I',correct:0},{value:'E',correct:0},{value:'Z',correct:0},{value:'O',correct:0},{value:'A',correct:0},{value:'A',correct:0}],
[{value:'O',correct:0},{value:'O',correct:0},{value:'E',correct:0},{value:'M',correct:0},{value:'B',correct:0},{value:'H',correct:0},{value:'C',correct:0},{value:'C',correct:0},{value:'U',correct:0},{value:'A',correct:0},{value:'S',correct:0},{value:'I',correct:0},{value:'L',correct:0},{value:'E',correct:0},{value:'P',correct:0},{value:'Ñ',correct:0},{value:'T',correct:0},{value:'N',correct:0},{value:'Y',correct:0},{value:'A',correct:0},{value:'C',correct:0},{value:'I',correct:0},{value:'M',correct:0},{value:'O',correct:0},{value:'A',correct:0},{value:'B',correct:0},{value:'T',correct:0},{value:'A',correct:0},{value:'P',correct:0},{value:'N',correct:0}],
[{value:'I',correct:0},{value:'R',correct:0},{value:'O',correct:0},{value:'G',correct:0},{value:'R',correct:0},{value:'U',correct:0},{value:'O',correct:0},{value:'A',correct:0},{value:'N',correct:0},{value:'I',correct:0},{value:'L',correct:0},{value:'R',correct:0},{value:'E',correct:0},{value:'T',correct:0},{value:'S',correct:0},{value:'E',correct:0},{value:'E',correct:0},{value:'A',correct:0},{value:'T',correct:0},{value:'I',correct:0},{value:'Z',correct:0},{value:'E',correct:0},{value:'A',correct:0},{value:'A',correct:0},{value:'C',correct:0},{value:'G',correct:0},{value:'I',correct:0},{value:'O',correct:0},{value:'R',correct:0},{value:'I',correct:0}],
[{value:'C',correct:0},{value:'I',correct:0},{value:'D',correct:0},{value:'R',correct:0},{value:'E',correct:0},{value:'G',correct:0},{value:'L',correct:0},{value:'T',correct:0},{value:'O',correct:0},{value:'R',correct:0},{value:'E',correct:0},{value:'H',correct:0},{value:'C',correct:0},{value:'A',correct:0},{value:'L',correct:0},{value:'U',correct:0},{value:'P',correct:0},{value:'O',correct:0},{value:'P',correct:0},{value:'E',correct:0},{value:'Ñ',correct:0},{value:'I',correct:0},{value:'D',correct:0},{value:'R',correct:0},{value:'T',correct:0},{value:'S',correct:0},{value:'U',correct:0},{value:'T',correct:0},{value:'P',correct:0},{value:'M',correct:0}],
[{value:'A',correct:0},{value:'Z',correct:0},{value:'O',correct:0},{value:'O',correct:0},{value:'S',correct:0},{value:'O',correct:0},{value:'F',correct:0},{value:'F',correct:0},{value:'Z',correct:0},{value:'A',correct:0},{value:'P',correct:0},{value:'B',correct:0},{value:'C',correct:0},{value:'U',correct:0},{value:'M',correct:0},{value:'P',correct:0},{value:'L',correct:0},{value:'I',correct:0},{value:'D',correct:0},{value:'A',correct:0},{value:'M',correct:0},{value:'E',correct:0},{value:'N',correct:0},{value:'T',correct:0},{value:'E',correct:0},{value:'O',correct:0},{value:'I',correct:0},{value:'J',correct:0},{value:'L',correct:0},{value:'A',correct:0}],
[{value:'T',correct:0},{value:'A',correct:0},{value:'U',correct:0},{value:'D',correct:0},{value:'C',correct:0},{value:'P',correct:0},{value:'S',correct:0},{value:'T',correct:0},{value:'H',correct:0},{value:'A',correct:0},{value:'R',correct:0},{value:'U',correct:0},{value:'D',correct:0},{value:'A',correct:0},{value:'H',correct:0},{value:'C',correct:0},{value:'O',correct:0},{value:'R',correct:0},{value:'B',correct:0},{value:'G',correct:0},{value:'M',correct:0},{value:'E',correct:0},{value:'L',correct:0},{value:'O',correct:0},{value:'N',correct:0},{value:'R',correct:0},{value:'S',correct:0},{value:'P',correct:0},{value:'A',correct:0},{value:'L',correct:0}],
[{value:'I',correct:0},{value:'C',correct:0},{value:'D',correct:0},{value:'A',correct:0},{value:'A',correct:0},{value:'L',correct:0},{value:'E',correct:0},{value:'A',correct:0},{value:'S',correct:0},{value:'A',correct:0},{value:'R',correct:0},{value:'B',correct:0},{value:'V',correct:0},{value:'O',correct:0},{value:'I',correct:0},{value:'R',correct:0},{value:'A',correct:0},{value:'D',correct:0},{value:'I',correct:0},{value:'L',correct:0},{value:'O',correct:0},{value:'S',correct:0},{value:'J',correct:0},{value:'W',correct:0},{value:'T',correct:0},{value:'I',correct:0},{value:'W',correct:0},{value:'O',correct:0},{value:'E',correct:0},{value:'S',correct:0}],
[{value:'V',correct:0},{value:'I',correct:0},{value:'I',correct:0},{value:'T',correct:0},{value:'R',correct:0},{value:'E',correct:0},{value:'D',correct:0},{value:'L',correct:0},{value:'A',correct:0},{value:'L',correct:0},{value:'E',correct:0},{value:'U',correct:0},{value:'Z',correct:0},{value:'E',correct:0},{value:'B',correct:0},{value:'A',correct:0},{value:'C',correct:0},{value:'A',correct:0},{value:'H',correct:0},{value:'T',correct:0},{value:'A',correct:0},{value:'R',correct:0},{value:'E',correct:0},{value:'H',correct:0},{value:'C',correct:0},{value:'N',correct:0},{value:'A',correct:0},{value:'C',correct:0},{value:'G',correct:0},{value:'J',correct:0}],
[{value:'N',correct:0},{value:'O',correct:0},{value:'S',correct:0},{value:'E',correct:0},{value:'U',correct:0},{value:'K',correct:0},{value:'O',correct:0},{value:'E',correct:0},{value:'C',correct:0},{value:'A',correct:0},{value:'N',correct:0},{value:'I',correct:0},{value:'C',correct:0},{value:'O',correct:0},{value:'P',correct:0},{value:'A',correct:0},{value:'O',correct:0},{value:'I',correct:0},{value:'R',correct:0},{value:'A',correct:0},{value:'F',correct:0},{value:'A',correct:0},{value:'R',correct:0},{value:'G',correct:0},{value:'O',correct:0},{value:'R',correct:0},{value:'I',correct:0},{value:'U',correct:0},{value:'Q',correct:0},{value:'Y',correct:0}],
[{value:'I',correct:0},{value:'N',correct:0},{value:'A',correct:0},{value:'R',correct:0},{value:'N',correct:0},{value:'O',correct:0},{value:'I',correct:0},{value:'C',correct:0},{value:'A',correct:0},{value:'S',correct:0},{value:'R',correct:0},{value:'E',correct:0},{value:'V',correct:0},{value:'N',correct:0},{value:'O',correct:0},{value:'C',correct:0},{value:'L',correct:0},{value:'W',correct:0},{value:'R',correct:0},{value:'A',correct:0},{value:'G',correct:0},{value:'U',correct:0},{value:'Y',correct:0},{value:'B',correct:0},{value:'U',correct:0},{value:'S',correct:0},{value:'I',correct:0},{value:'S',correct:0},{value:'T',correct:0},{value:'J',correct:0}]]

export default class WordSearch extends React.Component{
  constructor(props) {
    super(props);
    this.state= {
    };
  }

  render(){

    return (
      <>
      <h1>WordSearch #1</h1>
      <WordSearchComponent completed={wordsearch}/>
      </>
    )
  }
};
